language: node_js
sudo: false
node_js:
  - '12'
  - '10'
  - '8'
branches:
  only:
    - dev
cache:
  npm: false
services:
  - mongodb
os:
  - windows
before_script:
  - cp config.env .env
install:
  - cd istanbul-mocha && npm install && cd ..
script:
  - cd istanbul-mocha && npm test
